### ISSUE TITLE
Execution of Thunkserver sample in FSI

### ISSUE THREAD

**Issue by ordinaryorange** [mbraceproject/Vagabond#24]
Running VS 2019 on windows 10.
Clone Vagabond.
Restore and Build
Highlight lines 14-25 of thunkServer.fsx
Alt+Enter to throw into FSI.

Get the following error in FSI
```
System.MissingMethodException: Method not found: '!!0 Microsoft.FSharp.Control.FSharpAsync.RunSynchronously(Microsoft.FSharp.Control.FSharpAsync`1<!!0>, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Microsoft.FSharp.Core.FSharpOption`1<System.Threading.CancellationToken>)'.
   at ThunkServer.ThunkClient.InitLocal()
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
Stopped due to error
```

Thought it was some sort of BindingRedirect issue, but cannot seem to get around it.

Have managed to get the Thunkserver working via an alternative method, so not super critical to have the FSI route specifically resolved.

Am more interested to learn why FSI cant find the method, to improve my overall F# knowledge

**Comment by eiriktsarpalis** [comment]
FSI on Visual Studio still runs on the old .NET framework, which is not supported by latest versions of Vagabond. You'd need to use an editor that runs the dotnet core equivalent, like ionide or Rider.
