### ISSUE TITLE
Partial trust

### ISSUE THREAD

**Issue by buybackoff** [mbraceproject/Vagabond#8]
Could you please add an option to execute an assembly in a partial trust? E.g. if I want to read or delete files in the ThunkServer sample then that action should fail. It is easy to do for a standalone app domain http://stackoverflow.com/a/1761491/801189, but I am not sure how to do it in this library.

**Comment by eiriktsarpalis** [comment]
Vagabond does not manage AppDomains on its own, it simply loads required dependencies on whatever AppDomain it happens to be running in. So you would need to manually create an AppDomain with the desired permissions and then set up an instance of Vagabond to run from there.

**Comment by buybackoff** [comment]
Thanks! So if I want different permissions for different thunks then several instances of Vagabond is the simplest solution?

**Comment by eiriktsarpalis** [comment]
Yes. The library does contain an "AppDomainPool" implementation as an extension, but I have not added support for custom permissions. Will add it now.

**Comment by dsyme** [comment]
I don't think this is ever going to be done. Partial trust is not even present in .NET Core for example
